import { StoreSetting, StoreSettingType } from 'src/entities/store-setting.entity';
import { StoreUser } from 'src/entities/store-user.entity';

export function getDefaultStoreSettings(
  storeId: number,
  createdBy?: StoreUser,
): Partial<StoreSetting>[] {
  return [
    {
      key: 'store.currency',
      value: 'USD',
      type: StoreSettingType.STRING,
      description: 'Default currency used in transactions',
      isEditable: true,
      isSystem: true,
      storeId,
      createdById: createdBy?.id,
    },
    {
      key: 'store.timezone',
      value: 'Africa/Douala',
      type: StoreSettingType.STRING,
      description: 'Default timezone for store operations',
      isEditable: true,
      isSystem: true,
      storeId,
      createdById: createdBy?.id,
    },
    {
      key: 'store.language',
      value: 'en',
      type: StoreSettingType.STRING,
      description: 'Language used in the user interface',
      isEditable: true,
      isSystem: true,
      storeId,
      createdById: createdBy?.id,
    },
    {
      key: 'store.country_code',
      value: 'US',
      type: StoreSettingType.STRING,
      description: 'Country where the store is located',
      isEditable: true,
      isSystem: true,
      storeId,
      createdById: createdBy?.id,
    },
    {
      key: 'store.tax_enabled',
      value: 'false',
      type: StoreSettingType.BOOLEAN,
      description: 'Enable or disable tax calculations',
      isEditable: true,
      isSystem: true,
      storeId,
      createdById: createdBy?.id,
    },
    {
      key: 'store.tax_rate',
      value: '0.0',
      type: StoreSettingType.NUMBER,
      description: 'Default tax rate (e.g., 0.2 for 20%)',
      isEditable: true,
      isSystem: true,
      storeId,
      createdById: createdBy?.id,
    },
    {
      key: 'store.contact_email',
      value: '',
      type: StoreSettingType.STRING,
      description: 'Contact email address of the store',
      isEditable: true,
      isSystem: false,
      storeId,
      createdById: createdBy?.id,
    },
    {
      key: 'store.website_url',
      value: '',
      type: StoreSettingType.STRING,
      description: 'Official website of the store',
      isEditable: true,
      isSystem: false,
      storeId,
      createdById: createdBy?.id,
    },
    {
      key: 'receipt.header',
      value: 'Welcome to our store!',
      type: StoreSettingType.STRING,
      description: 'Header message displayed on sales receipts',
      isEditable: true,
      isSystem: false,
      storeId,
      createdById: createdBy?.id,
    },
    {
      key: 'receipt.footer',
      value: 'Thank you for shopping with us!',
      type: StoreSettingType.STRING,
      description: 'Footer message displayed on sales receipts',
      isEditable: true,
      isSystem: false,
      storeId,
      createdById: createdBy?.id,
    },
    {
      key: 'receipt.show_logo',
      value: 'true',
      type: StoreSettingType.BOOLEAN,
      description: 'Show the store logo on sales receipts',
      isEditable: true,
      isSystem: false,
      storeId,
      createdById: createdBy?.id,
    },
  ];
}
